"""Authoritative entry defaults, separate from model defaults and analysis protocols.

Functions return fresh dictionaries. Callers supply explicit input identity/path
context; this module never imports runners, parses argv or selects a dataset.
Equal numeric values in different profiles are intentional entry defaults, not
fallbacks used to overwrite explicit configuration.
"""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

_ACCELERATED_PAIRED_EXECUTION = {
    'training_loss_only': True,
    'decoder_chunk_size': 2048,
    'ot_attention_source_chunk_size': 1024,
    'checkpoint_ot_attention': True,
    'checkpoint_encoder_fusion': True,
    'checkpoint_decoder_chunks': True,
    'checkpoint_graph_encoder': True,
    'amp_dtype': 'bf16',
    'cache_spatial_graphs': True,
    'save_candidate_qc': True,
    'save_outputs': True,
    'save_embeddings': True,
    'save_ot_prior_topk': True,
    'log_cuda_memory': True,
}

MOUSEBRAIN_MODEL_DEFAULTS = {"training": {"epochs": 5}, "uot": {"max_iter": 100}}

MOUSEBRAIN_UOT_HELPER_DEFAULTS = {
    "candidate_backend": "faiss_ivf",
    "initial_modality_candidate_k": 100,
    "candidate_k": 200,
    "faiss_nlist": 256,
    "faiss_nprobe": 32,
    "faiss_device": "auto",
    "faiss_train_sample_size": 10000,
    "faiss_query_batch_size": 2048,
    "stabilizer": 1e-8,
}

MOUSEBRAIN_TRAINING_DEFAULTS = {
    "seed": 42,
    "max_spots_per_section": None,
    "output_dir": str(PROJECT_ROOT / "results" / "mousebrain_test"),
}

SPATCH_TRAINING_DEFAULTS = {
    "training_loss_only": True,
    "checkpoint_ot_attention": True,
    "checkpoint_encoder_fusion": True,
    "checkpoint_decoder_chunks": True,
    "checkpoint_graph_encoder": True,
    "cache_spatial_graphs": True,
    "log_every": 1,
    "log_cuda_memory": True,
    "log_cuda_memory_detail": True,
    "save_candidate_qc": False,
}

GENERIC_SMOKE_DEFAULTS = {"epochs": 3, "device": "cpu", "uot_max_iter": 50}

GENERIC_CLI_DEFAULTS = {"log_every": 1, "save_every": 0, "candidate_backend": "faiss_ivf"}

def crc_defaults():
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'data_dir': "/home/hujinlan/spa_mo_model/data/CRC_Stereo-CITE-seq",
        'max_spots_per_section': None,
        'max_shared_genes': 3000,
        'spot_sampling': "first",
        'train': False,
        'epochs': 0,
        'lambda_contrast': None,
        'lr': 1e-3,
        'weight_decay': 0.0,
        'update_interval': 20,
        'log_every': 1,
        'device': "cpu",
        'candidate_backend': "faiss_ivf",
        'initial_modality_candidate_k': 100,
        'candidate_k': 200,
        'attention_topk': 10,
        'faiss_nlist': 4096,
        'faiss_nprobe': 64,
        'faiss_device': "auto",
        'faiss_train_sample_size': 100000,
        'faiss_query_batch_size': 8192,
        'uot_epsilon': 0.05,
        'uot_tau_a': 1.0,
        'uot_tau_b': 1.0,
        'uot_stabilizer': 1e-8,
        'spatial_knn_k': 5,
        'graphsage_edge_batch_size': 200000,
        'post_ot_graphsage_scale': 1.0,
        'training_loss_only': False,
        'decoder_chunk_size': 0,
        'ot_attention_source_chunk_size': 0,
        'checkpoint_ot_attention': False,
        'checkpoint_encoder_fusion': False,
        'checkpoint_decoder_chunks': False,
        'checkpoint_graph_encoder': False,
        'amp_dtype': "none",
        'cache_spatial_graphs': False,
        'save_candidate_qc': False,
        'save_outputs': False,
        'save_embeddings': False,
        'save_ot_prior_topk': False,
        'log_cuda_memory': False,
        'log_cuda_memory_detail': False,
        'output_dir': "/home/hujinlan/spa_mo_model/results/crc_stereocite/dry_run_make_unique_pipeline",
        'seed': 0,
        'n_comps': 50,
        'hvg_num': 3000,
        'uot_max_iter': 100,
        'no_harmony': False,
    }


def misar_defaults(*, dataset_name="MISAR-seq", secondary_name="atac", section_order):
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'data_dir': f"/home/hujinlan/spa_mo_model/data/{dataset_name}",
        'section_order': ",".join(section_order),
        'max_spots_per_section': None,
        'spot_sampling': "first",
        'max_shared_genes': None,
        'max_shared_peaks': None,
        'train': False,
        'epochs': 0,
        'lambda_contrast': None,
        'lr': 1e-3,
        'weight_decay': 0.0,
        'update_interval': 20,
        'log_every': 1,
        'device': "cpu",
        'candidate_backend': "faiss_ivf",
        'initial_modality_candidate_k': 100,
        'candidate_k': 200,
        'attention_topk': 10,
        'faiss_nlist': 256,
        'faiss_nprobe': 32,
        'faiss_device': "auto",
        'faiss_train_sample_size': 20000,
        'faiss_query_batch_size': 2048,
        'uot_epsilon': 0.05,
        'uot_tau_a': 1.0,
        'uot_tau_b': 1.0,
        'uot_stabilizer': 1e-8,
        'uot_max_iter': 100,
        'spatial_knn_k': 5,
        'graphsage_edge_batch_size': 50000,
        'post_ot_graphsage_scale': 1.0,
        'graphsage_dropout': 0.1,
        'encoder_dropout': 0.1,
        'fusion_dropout': 0.1,
        'ot_attention_dropout': 0.1,
        'decoder_dropout': 0.1,
        'training_loss_only': False,
        'decoder_chunk_size': 50000,
        'ot_attention_source_chunk_size': 50000,
        'checkpoint_ot_attention': False,
        'checkpoint_encoder_fusion': False,
        'checkpoint_decoder_chunks': False,
        'checkpoint_graph_encoder': False,
        'amp_dtype': "none",
        'cache_spatial_graphs': False,
        'save_candidate_qc': False,
        'save_outputs': False,
        'save_embeddings': False,
        'save_ot_prior_topk': False,
        'log_cuda_memory': False,
        'log_cuda_memory_detail': False,
        'output_dir': "/home/hujinlan/spa_mo_model/results/misar_seq/dry_run",
        'seed': 0,
        'n_comps': 50,
        'hvg_num': 3000,
        f'hvg_num_{secondary_name}': 3000,
        'no_harmony': False,
    }


def paired_rna_protein_defaults(*, data_dir, output_dir):
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'data_dir': str(data_dir),
        'output_dir': str(output_dir),
        'train': True,
        'epochs': 200,
        'seed': 42,
        'device': 'cuda',
        'max_shared_genes': 20000,
        'hvg_num': 3000,
        'lambda_contrast': 0.1,
        'candidate_backend': 'faiss_ivf',
        'faiss_nlist': 256,
        'faiss_nprobe': 32,
        'faiss_train_sample_size': 10000,
        'faiss_query_batch_size': 2048,
        'initial_modality_candidate_k': 100,
        'candidate_k': 200,
        'attention_topk': 10,
        'spatial_knn_k': 10,
        'graphsage_edge_batch_size': 100000,
        **_ACCELERATED_PAIRED_EXECUTION,
    }


def thymus_defaults(*, data_dir, output_dir, sections, marker_count):
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        "data_dir": str(data_dir),
        "output_dir": str(output_dir),
        "section_order": ",".join(sections),
        "train": True,
        "epochs": 200,
        "seed": 42,
        "device": "cuda",
        "hvg_num": 3000,
        "hvg_num_adt": marker_count,
        "lambda_contrast": 0.1,
        "candidate_backend": "faiss_ivf",
        "faiss_nlist": 256,
        "faiss_nprobe": 32,
        "faiss_train_sample_size": 10000,
        "faiss_query_batch_size": 2048,
        "initial_modality_candidate_k": 100,
        "candidate_k": 200,
        "attention_topk": 10,
        "spatial_knn_k": 10,
        "graphsage_edge_batch_size": 100000,
        **_ACCELERATED_PAIRED_EXECUTION,
    }


def simulation_defaults(*, data_dir, output_dir, sections):
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        "data_dir": str(data_dir),
        "output_dir": str(output_dir),
        "section_order": ",".join(sections),
        "train": True,
        "epochs": 200,
        "seed": 42,
        "device": "cuda",
        "hvg_num": 1000,
        "hvg_num_adt": 100,
        "lambda_contrast": 0.1,
        "candidate_backend": "faiss_flat",
        "initial_modality_candidate_k": 100,
        "candidate_k": 200,
        "attention_topk": 10,
        "spatial_knn_k": 10,
        "graphsage_edge_batch_size": 100000,
        **_ACCELERATED_PAIRED_EXECUTION,
    }


def mousebrain_defaults():
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'config': None,
        'dry_run': False,
        'epochs': None,
        'max_spots_per_section': None,
        'lambda_contrast': None,
        'lambda_contrast_schedule': None,
        'device': None,
        'output_dir': None,
        'seed': None,
        'candidate_backend': None,
        'initial_modality_candidate_k': None,
        'candidate_k': None,
        'attention_topk': None,
        'faiss_nlist': None,
        'faiss_nprobe': None,
        'faiss_device': None,
        'faiss_train_sample_size': None,
        'faiss_query_batch_size': None,
        'uot_epsilon': None,
        'uot_tau_a': None,
        'uot_tau_b': None,
        'uot_max_iter': None,
        'uot_stabilizer': None,
        'update_interval': None,
        'spatial_knn_k': None,
        'post_ot_graphsage_scale': None,
        'save_ot_prior_topk': False,
        'ot_prior_output_dir': None,
    }


def embryo_defaults():
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'data_dir': "/home/hujinlan/human_embryo",
        'output_dir': "/home/hujinlan/spa_mo_model/results/human_embryo_rna_only",
        'preprocess_only': False,
        'dry_run': False,
        'train': False,
        'single_modality': "RNA",
        'reuse_preprocessed': False,
        'preprocessed_run_dir': None,
        'require_harmony': False,
        'hvg_num': 3000,
        'hvg_sample_per_section': 5000,
        'svd_fit_per_section': 20000,
        'n_comps': 50,
        'target_sum': 10000.0,
        'min_counts': 10.0,
        'min_genes': 5,
        'max_pct_mt': 30.0,
        'max_spots_per_section': None,
        'source_chunk_rows': 4096,
        'epochs': 100,
        'lr': 1e-3,
        'weight_decay': 0.0,
        'device': "cuda",
        'seed': 42,
        'log_every': 1,
        'update_interval': 20,
        'uot_max_iter': 100,
        'uot_epsilon': 0.05,
        'uot_tau_a': 1.0,
        'uot_tau_b': 1.0,
        'uot_stabilizer': 1e-8,
        'disable_uot': False,
        'candidate_backend': "faiss_ivf",
        'initial_modality_candidate_k': 100,
        'candidate_k': 200,
        'attention_topk': 10,
        'faiss_nlist': 4096,
        'faiss_nprobe': 64,
        'faiss_device': "auto",
        'faiss_train_sample_size': 100000,
        'faiss_query_batch_size': 2048,
        'spatial_knn_k': 5,
        'graphsage_edge_batch_size': 200000,
        'decoder_chunk_size': 50000,
        'ot_attention_source_chunk_size': 50000,
        'training_loss_only': True,
        'checkpoint_ot_attention': True,
        'checkpoint_encoder_fusion': True,
        'checkpoint_decoder_chunks': True,
        'checkpoint_graph_encoder': True,
        'cache_spatial_graphs': True,
        'amp_dtype': "bf16",
        'save_candidate_qc': False,
        'log_cuda_memory': False,
        'log_cuda_memory_detail': False,
        'lambda_contrast': 0.0,
    }


def spatch_defaults():
    """Return the existing entry defaults; absent/None semantics stay with parsing."""
    return {
        'input_mode': 'reuse',
        'output_cache_dir': None,
        'data_dir': None,
        'input_identity_manifest': None,
        'output_dir': PROJECT_ROOT / "results" / "spatch" / "fullspot_200ep_gpu_seed42",
        'epochs': 200,
        'seed': 42,
        'device': "cuda",
        'n_comps': 50,
        'hvg_num': 3000,
        'lr': 1e-3,
        'weight_decay': 0.0,
        'lambda_contrast': 0.1,
        'update_interval': 20,
        'uot_max_iter': 100,
        'candidate_backend': "faiss_ivf",
        'initial_modality_candidate_k': 100,
        'candidate_k': 200,
        'attention_topk': 10,
        'faiss_nlist': 4096,
        'faiss_nprobe': 64,
        'faiss_device': "gpu",
        'faiss_train_sample_size': 100000,
        'faiss_query_batch_size': 2048,
        'uot_epsilon': 0.05,
        'uot_tau_a': 1.0,
        'uot_tau_b': 1.0,
        'uot_stabilizer': 1e-8,
        'spatial_knn_k': 10,
        'graphsage_edge_batch_size': 100000,
        'decoder_chunk_size': 8192,
        'ot_attention_source_chunk_size': 2048,
        'amp_dtype': "bf16",
        'post_ot_graphsage_scale': 1.0,
        'preprocessed_cache_dir': None,
        'build_preprocessed_cache': False,
        'no_harmony': False,
        'overwrite': False,
    }


